package br.com.uemg.autopecas.view;

import br.com.uemg.autopecas.DAO.CategoriaDAO;
import br.com.uemg.autopecas.DAO.FornecedorDAO;
import br.com.uemg.autopecas.controller.ConnectionFactory;
import br.com.uemg.autopecas.model.Categoria;
import br.com.uemg.autopecas.model.Fornecedor;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gustavo
 */
public final class CategoriaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaClienteView
     */
    FornecedorView ccview = new FornecedorView();
    public int transacao;

    public CategoriaView() {
        initComponents();
        DefaultTableModel ListaCategoria = (DefaultTableModel) TabelaCategorias.getModel();
        TabelaCategorias.setRowSorter(new TableRowSorter(ListaCategoria));

        TabelaCategorias.getColumnModel().getColumn(0).setPreferredWidth(40);
        TabelaCategorias.getColumnModel().getColumn(1).setPreferredWidth(250);
        read();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelConsultaClientes = new javax.swing.JPanel();
        TextoDescricao = new javax.swing.JTextField();
        LabelArgumento = new javax.swing.JLabel();
        ScrollPainel = new javax.swing.JScrollPane();
        TabelaCategorias = new javax.swing.JTable();
        BotaoConsultar = new javax.swing.JButton();
        TextoCodigo = new javax.swing.JTextField();
        LabelCodigo = new javax.swing.JLabel();
        BotaoNovo = new javax.swing.JButton();
        BotaoGravar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18)), "Categorias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N
        setClosable(true);
        setForeground(java.awt.Color.white);
        setName(""); // NOI18N
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        TextoDescricao.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        LabelArgumento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelArgumento.setText("Descrição:");

        TabelaCategorias.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        TabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCategoriasMouseClicked(evt);
            }
        });
        ScrollPainel.setViewportView(TabelaCategorias);

        BotaoConsultar.setBackground(new java.awt.Color(0, 102, 102));
        BotaoConsultar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoConsultar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoConsultar.setToolTipText("");
        BotaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarActionPerformed(evt);
            }
        });

        TextoCodigo.setEditable(false);
        TextoCodigo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        LabelCodigo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCodigo.setText("Código");

        javax.swing.GroupLayout PainelConsultaClientesLayout = new javax.swing.GroupLayout(PainelConsultaClientes);
        PainelConsultaClientes.setLayout(PainelConsultaClientesLayout);
        PainelConsultaClientesLayout.setHorizontalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPainel)
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCodigo)
                            .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelArgumento)
                            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                                .addComponent(TextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelConsultaClientesLayout.setVerticalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addComponent(LabelArgumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoDescricao)))
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addComponent(LabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotaoNovo.setBackground(new java.awt.Color(0, 102, 102));
        BotaoNovo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoNovo.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-add-icon_34367.png"))); // NOI18N
        BotaoNovo.setText("Novo");
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });

        BotaoGravar.setBackground(new java.awt.Color(0, 102, 102));
        BotaoGravar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoGravar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-check-icon_34365.png"))); // NOI18N
        BotaoGravar.setText("Gravar");
        BotaoGravar.setEnabled(false);
        BotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarActionPerformed(evt);
            }
        });

        BotaoCancelar.setBackground(new java.awt.Color(204, 0, 0));
        BotaoCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-error-icon_34362.png"))); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.setEnabled(false);
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        BotaoEditar.setBackground(new java.awt.Color(51, 102, 255));
        BotaoEditar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoEditar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/pencil-icon_34383.png"))); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.setEnabled(false);
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });

        BotaoExcluir.setBackground(new java.awt.Color(204, 0, 0));
        BotaoExcluir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        BotaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/trashcan-full-icon_34338.png"))); // NOI18N
        BotaoExcluir.setText("Excluir");
        BotaoExcluir.setEnabled(false);
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelConsultaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoGravar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelConsultaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGravar)
                    .addComponent(BotaoCancelar)
                    .addComponent(BotaoEditar)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoNovo))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        setBounds(250, 250, 690, 422);
    }// </editor-fold>//GEN-END:initComponents

    public void read() {
        try (Connection connection = new ConnectionFactory().getConnection()) {
            DefaultTableModel ListaCategoria = (DefaultTableModel) TabelaCategorias.getModel();
            ListaCategoria.setNumRows(0);

            CategoriaDAO dao = new CategoriaDAO(connection);

            for (Categoria c : dao.read()) {

                ListaCategoria.addRow(new Object[]{
                    c.getId(),
                    c.getDescricao()});

            }

        } catch (SQLException ex) {
            Logger.getLogger(CategoriaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void read(String busca) {
        try (Connection connection = new ConnectionFactory().getConnection()) {
            DefaultTableModel ListaCategoria = (DefaultTableModel) TabelaCategorias.getModel();
            ListaCategoria.setNumRows(0);

            CategoriaDAO dao = new CategoriaDAO(connection);

            for (Categoria c : dao.read(busca)) {
                //**/

                ListaCategoria.addRow(new Object[]{
                    c.getId(),
                    c.getDescricao()});

                System.out.println(c);

            }

        } catch (SQLException ex) {
            Logger.getLogger(CategoriaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

        if (TabelaCategorias.getSelectedRow() != 0) {

            TabelaCategorias.getValueAt(TabelaCategorias.getSelectedRow(), 1).toString();
            TabelaCategorias.getValueAt(TabelaCategorias.getSelectedRow(), 2).toString();

        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void TabelaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCategoriasMouseClicked
        Categoria c = new Categoria();

        c.setId(Integer.parseInt(TabelaCategorias.getValueAt(TabelaCategorias.getSelectedRow(), 0).toString()));
        c.setDescricao(TabelaCategorias.getValueAt(TabelaCategorias.getSelectedRow(), 1).toString());

        capturar(c);

        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaCategoriasMouseClicked
    public void capturar(Categoria c) {

        System.out.println("método capturar(): " + c.getId());

        TextoCodigo.setText(String.valueOf(c.getId()));
        TextoDescricao.setText(c.getDescricao());
        BotaoEditar.setEnabled(true);

    }
    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        // TODO add your handling code here:
        transacao = 0;

        TextoCodigo.setEnabled(false);
        BotaoNovo.setEnabled(false);
        BotaoEditar.setEnabled(false);
        BotaoGravar.setEnabled(true);
        limpar();

    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void BotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarActionPerformed

        if (TextoDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Categoria sem descrição!");
        } else {
            gravar();
        }

        BotaoNovo.setEnabled(true);
        BotaoEditar.setEnabled(true);
    }//GEN-LAST:event_BotaoGravarActionPerformed

    public void gravar() {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            CategoriaDAO dao = new CategoriaDAO(connection);
            if (transacao == 0) {
                dao.create(new Categoria(null, TextoDescricao.getText()));

                JOptionPane.showMessageDialog(null, "Gravado no banco de dados!");
                limpar();
                read();

            }
            if (transacao == 1) {
                dao.update(new Categoria(Integer.valueOf(TextoCodigo.getText()),
                        TextoDescricao.getText()));

                JOptionPane.showMessageDialog(null, "Gravado no banco de dados!");
                limpar();
                read();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
    }

    public void limpar() {
        TextoCodigo.setText("");
        TextoDescricao.setText("");
    }

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:

        BotaoNovo.setEnabled(true);
        BotaoEditar.setEnabled(true);
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        transacao = 1;

        TextoCodigo.setEnabled(false);
        BotaoEditar.setEnabled(false);
        BotaoNovo.setEnabled(false);
        BotaoGravar.setEnabled(true);
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    public void excluir() {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            if (JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?", "Confirmação de exclusão!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                CategoriaDAO dao = new CategoriaDAO(connection);
                Categoria c = new Categoria();

                Integer id = Integer.valueOf(
                        TextoCodigo.getText());

                c.setId(id);
                dao.delete(c);
                limpar();
            }

            JOptionPane.showMessageDialog(null, "Excluído no Banco de Dados");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
    }

    private void BotaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarActionPerformed
        read(TextoDescricao.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoConsultar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JLabel LabelArgumento;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JPanel PainelConsultaClientes;
    private javax.swing.JScrollPane ScrollPainel;
    private javax.swing.JTable TabelaCategorias;
    public static javax.swing.JTextField TextoCodigo;
    private javax.swing.JTextField TextoDescricao;
    // End of variables declaration//GEN-END:variables
}
