/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.uemg.autopecas.view;

import br.com.uemg.autopecas.DAO.ClienteDAO;
import br.com.uemg.autopecas.controller.ConnectionFactory;
import br.com.uemg.autopecas.model.Cliente;
import br.com.uemg.autopecas.model.Pessoa;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class ClienteView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public ClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNome = new javax.swing.JLabel();
        TextoNome = new javax.swing.JTextField();
        Painel = new javax.swing.JTabbedPane();
        PainelInformacoesPessoais = new javax.swing.JPanel();
        TextoFormatadoNascimento = new javax.swing.JFormattedTextField();
        LabelApelido = new javax.swing.JLabel();
        TextoApelido = new javax.swing.JTextField();
        LabelTipo = new javax.swing.JLabel();
        LabelInscricao = new javax.swing.JLabel();
        TextoFormatadoInscricao = new javax.swing.JFormattedTextField();
        LabelDataNascimento = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        LabelContato = new javax.swing.JLabel();
        TextoContato = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JTextField();
        PainelEndereco = new javax.swing.JPanel();
        LabelCEP = new javax.swing.JLabel();
        TextoFormatadoCEP = new javax.swing.JFormattedTextField();
        LabelLogradouro = new javax.swing.JLabel();
        TextoLogradouro = new javax.swing.JTextField();
        LabelBairro = new javax.swing.JLabel();
        TextoBairro = new javax.swing.JTextField();
        TextoCidade = new javax.swing.JTextField();
        LabelCidade = new javax.swing.JLabel();
        ComboBoxUF = new javax.swing.JComboBox<>();
        LabelUF = new javax.swing.JLabel();
        BotaoGravar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextoCodigo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(181, 223, 242));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setForeground(java.awt.Color.black);
        setResizable(true);
        setTitle("Cadastro de Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setVisible(true);

        LabelNome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelNome.setText("Nome Completo:");

        Painel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Painel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        try {
            TextoFormatadoNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LabelApelido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelApelido.setText("Apelido:");

        TextoApelido.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        TextoApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoApelidoActionPerformed(evt);
            }
        });

        LabelTipo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelTipo.setText("Tipo:");

        LabelInscricao.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelInscricao.setText("Inscrição:");

        TextoFormatadoInscricao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        TextoFormatadoInscricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoFormatadoInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoFormatadoInscricaoActionPerformed(evt);
            }
        });

        LabelDataNascimento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelDataNascimento.setText("Data Nascimento:");

        ComboBoxTipo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "CNPJ" }));

        LabelContato.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelContato.setText("Contato:");

        LabelEmail.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelEmail.setText("E-mail:");

        javax.swing.GroupLayout PainelInformacoesPessoaisLayout = new javax.swing.GroupLayout(PainelInformacoesPessoais);
        PainelInformacoesPessoais.setLayout(PainelInformacoesPessoaisLayout);
        PainelInformacoesPessoaisLayout.setHorizontalGroup(
            PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoApelido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTipo)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelInscricao)
                            .addComponent(TextoFormatadoInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoFormatadoNascimento)))
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addComponent(LabelApelido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelContato)
                            .addComponent(TextoContato, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEmail)
                            .addComponent(TextoEmail))))
                .addContainerGap())
        );
        PainelInformacoesPessoaisLayout.setVerticalGroup(
            PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LabelApelido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelInscricao)
                            .addComponent(LabelTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFormatadoInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoFormatadoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelContato)
                    .addComponent(LabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Painel.addTab("Informações Pessoais", PainelInformacoesPessoais);

        LabelCEP.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCEP.setText("CEP:");

        try {
            TextoFormatadoCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LabelLogradouro.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelLogradouro.setText("Logradouro:");

        TextoLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoLogradouroActionPerformed(evt);
            }
        });

        LabelBairro.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelBairro.setText("Bairro:");

        LabelCidade.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCidade.setText("Cidade:");

        ComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        LabelUF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelUF.setText("UF:");

        javax.swing.GroupLayout PainelEnderecoLayout = new javax.swing.GroupLayout(PainelEndereco);
        PainelEndereco.setLayout(PainelEnderecoLayout);
        PainelEnderecoLayout.setHorizontalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(TextoCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextoLogradouro)
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                                .addComponent(LabelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 547, Short.MAX_VALUE))
                            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                                .addComponent(TextoBairro)
                                .addGap(12, 12, 12)))
                        .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                                .addComponent(LabelCEP)
                                .addGap(79, 79, 79))
                            .addComponent(TextoFormatadoCEP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLogradouro)
                            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                                .addComponent(LabelCidade)
                                .addGap(277, 277, 277)
                                .addComponent(LabelUF)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelEnderecoLayout.setVerticalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLogradouro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBairro)
                    .addComponent(LabelCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoFormatadoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCidade)
                    .addComponent(LabelUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Painel.addTab("Endereço", PainelEndereco);

        BotaoGravar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoGravar.setText("Gravar");
        BotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        TextoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Painel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BotaoGravar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(38, 38, 38)
                                        .addComponent(LabelNome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoGravar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoApelidoActionPerformed

    private void TextoLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoLogradouroActionPerformed

    private void TextoFormatadoInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoFormatadoInscricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoFormatadoInscricaoActionPerformed

    private void BotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarActionPerformed

        try (Connection connection = new ConnectionFactory().getConnection()) {

            ClienteDAO cd = new ClienteDAO(connection);
            cd.create(new Cliente(
                    0, new Pessoa(
                            (String) ComboBoxTipo.getSelectedItem(),
                            TextoFormatadoInscricao.getText(),
                            TextoNome.getText(),
                            TextoApelido.getText(),
                            TextoFormatadoNascimento.getText(),
                            TextoLogradouro.getText(),
                            TextoBairro.getText(),
                            TextoCidade.getText(),
                            (String) ComboBoxUF.getSelectedItem(),
                            TextoFormatadoCEP.getText()
                    ),
                    TextoContato.getText(),
                    TextoEmail.getText()
            ));
            JOptionPane.showMessageDialog(null, "Gravado no banco de dados!");

            ComboBoxTipo.setSelectedItem(ABORT);
            TextoFormatadoInscricao.setText("");
            TextoNome.setText("");
            TextoApelido.setText("");
            TextoFormatadoNascimento.setText("");
            TextoLogradouro.setText("");
            TextoBairro.setText("");
            TextoCidade.setText("");
            ComboBoxUF.setSelectedItem(ABORT);
            TextoFormatadoCEP.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotaoGravarActionPerformed

    private void TextoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JComboBox<String> ComboBoxUF;
    private javax.swing.JLabel LabelApelido;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelContato;
    private javax.swing.JLabel LabelDataNascimento;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelInscricao;
    private javax.swing.JLabel LabelLogradouro;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelUF;
    private javax.swing.JTabbedPane Painel;
    private javax.swing.JPanel PainelEndereco;
    private javax.swing.JPanel PainelInformacoesPessoais;
    private javax.swing.JTextField TextoApelido;
    private javax.swing.JTextField TextoBairro;
    private javax.swing.JTextField TextoCidade;
    private javax.swing.JTextField TextoCodigo;
    private javax.swing.JTextField TextoContato;
    private javax.swing.JTextField TextoEmail;
    private javax.swing.JFormattedTextField TextoFormatadoCEP;
    private javax.swing.JFormattedTextField TextoFormatadoInscricao;
    private javax.swing.JFormattedTextField TextoFormatadoNascimento;
    private javax.swing.JTextField TextoLogradouro;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
