/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.uemg.autopecas.view;

/**
 *
 * @author gustavo
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPanePrincipal = new javax.swing.JDesktopPane();
        MenuBarPrincipal = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuItemCliente = new javax.swing.JMenuItem();
        MenuItemFornecedor = new javax.swing.JMenuItem();
        MenuItemCategoria = new javax.swing.JMenuItem();
        MenuItemProduto = new javax.swing.JMenuItem();
        MenuPedido = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRACH AUTO PEÇAS");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        DesktopPanePrincipal.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DesktopPanePrincipalLayout = new javax.swing.GroupLayout(DesktopPanePrincipal);
        DesktopPanePrincipal.setLayout(DesktopPanePrincipalLayout);
        DesktopPanePrincipalLayout.setHorizontalGroup(
            DesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        DesktopPanePrincipalLayout.setVerticalGroup(
            DesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        MenuBarPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        MenuBarPrincipal.setBorder(null);
        MenuBarPrincipal.setToolTipText("");
        MenuBarPrincipal.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        MenuBarPrincipal.setInheritsPopupMenu(true);

        MenuCadastro.setText("CADASTRO");
        MenuCadastro.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        MenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroActionPerformed(evt);
            }
        });

        MenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuItemCliente.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        MenuItemCliente.setText("CLIENTE");
        MenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemCliente);

        MenuItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuItemFornecedor.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        MenuItemFornecedor.setText("FORNECEDOR");
        MenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFornecedorActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemFornecedor);

        MenuItemCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuItemCategoria.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        MenuItemCategoria.setText("CATEGORIA");
        MenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCategoriaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemCategoria);

        MenuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuItemProduto.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        MenuItemProduto.setText("PRODUTO");
        MenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProdutoActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemProduto);

        MenuBarPrincipal.add(MenuCadastro);

        MenuPedido.setText("PEDIDO");
        MenuPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        MenuBarPrincipal.add(MenuPedido);

        MenuSobre.setText("SOBRE");
        MenuSobre.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        MenuBarPrincipal.add(MenuSobre);

        setJMenuBar(MenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPanePrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClienteActionPerformed
        // TODO add your handling code here:

        ClienteView cliente = new ClienteView();
        DesktopPanePrincipal.add(cliente);
        cliente.setVisible(true);


    }//GEN-LAST:event_MenuItemClienteActionPerformed

    private void MenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadastroActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void MenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFornecedorActionPerformed
        // TODO add your handling code here:

        FornecedorView fornecedor = new FornecedorView();
        DesktopPanePrincipal.add(fornecedor);
        fornecedor.setVisible(true);

    }//GEN-LAST:event_MenuItemFornecedorActionPerformed

    private void MenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCategoriaActionPerformed
        // TODO add your handling code here:
        CategoriaView categoria = new CategoriaView();
        DesktopPanePrincipal.add(categoria);
        categoria.setVisible(true);
    }//GEN-LAST:event_MenuItemCategoriaActionPerformed

    private void MenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProdutoActionPerformed
        // TODO add your handling code here:
        ProdutoView produto = new ProdutoView();
        DesktopPanePrincipal.add(produto);
        produto.setVisible(true);
    }//GEN-LAST:event_MenuItemProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPanePrincipal;
    private javax.swing.JMenuBar MenuBarPrincipal;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuItemCategoria;
    private javax.swing.JMenuItem MenuItemCliente;
    private javax.swing.JMenuItem MenuItemFornecedor;
    private javax.swing.JMenuItem MenuItemProduto;
    private javax.swing.JMenu MenuPedido;
    private javax.swing.JMenu MenuSobre;
    // End of variables declaration//GEN-END:variables
}
