package br.com.uemg.autopecas.view;

import br.com.uemg.autopecas.DAO.CategoriaDAO;
import br.com.uemg.autopecas.DAO.ClienteDAO;
import br.com.uemg.autopecas.DAO.PedidoDAO;
import br.com.uemg.autopecas.DAO.PedidoProdutoDAO;
import br.com.uemg.autopecas.DAO.ProdutoDAO;
import br.com.uemg.autopecas.controller.ConnectionFactory;
import br.com.uemg.autopecas.model.Categoria;
import br.com.uemg.autopecas.model.Cliente;
import br.com.uemg.autopecas.model.Pedido;
import br.com.uemg.autopecas.model.PedidoProduto;
import br.com.uemg.autopecas.model.Produto;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gustavo
 */
public class VendaView extends javax.swing.JInternalFrame {

    public int transacao;

    /**
     * Creates new form Cliente
     *
     */
    public VendaView() {

        initComponents();
        TextoUsuario.setText(PrincipalView.usuario.getNome());

        DefaultTableModel produtos = (DefaultTableModel) TabelaProdutosAdicionados.getModel();
        TabelaProdutosAdicionados.setRowSorter(new TableRowSorter(produtos));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogCliente = new javax.swing.JDialog();
        LabelCliente = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        Painel = new javax.swing.JTabbedPane();
        PainelInformacoesPessoais = new javax.swing.JPanel();
        LabelPrecoVenda = new javax.swing.JLabel();
        LabelQuantidade = new javax.swing.JLabel();
        TextoFormatadoPrecoUnitario = new javax.swing.JFormattedTextField();
        TextoFormatadoQuantidade = new javax.swing.JFormattedTextField();
        LabelDesconto = new javax.swing.JLabel();
        TextoFormatadoDesconto = new javax.swing.JFormattedTextField();
        TextoCodigoProduto = new javax.swing.JTextField();
        TextoProduto = new javax.swing.JTextField();
        BotaoBuscarProduto = new javax.swing.JButton();
        LabelCodigoProduto = new javax.swing.JLabel();
        LabelProduto = new javax.swing.JLabel();
        LabelEstoque = new javax.swing.JLabel();
        TextoFormatadoEstoque = new javax.swing.JFormattedTextField();
        BotaoAdicionarProduto = new javax.swing.JButton();
        BotaoRetirarProduto = new javax.swing.JButton();
        BotaoGravar = new javax.swing.JButton();
        BotaoBuscarCliente = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        LabelUsuario = new javax.swing.JLabel();
        TextoCliente = new javax.swing.JTextField();
        LabelOrcamento = new javax.swing.JLabel();
        LabelCodigoCliente = new javax.swing.JLabel();
        TextoCodigoPedido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutosAdicionados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TextoFinalTotal = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        TextoFinalSubtotal = new javax.swing.JFormattedTextField();
        BotaoBuscarOrcamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxPagamento = new javax.swing.JComboBox<>();
        TextoFinalDesconto = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoCodigoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout DialogClienteLayout = new javax.swing.GroupLayout(DialogCliente.getContentPane());
        DialogCliente.getContentPane().setLayout(DialogClienteLayout);
        DialogClienteLayout.setHorizontalGroup(
            DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DialogClienteLayout.setVerticalGroup(
            DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Ordem de Vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N
        setClosable(true);
        setForeground(java.awt.Color.white);
        setResizable(true);
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInputVerifier(getInputVerifier());
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        LabelCliente.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCliente.setText("Cliente");

        TextoUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        TextoUsuario.setEnabled(false);

        Painel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Painel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        Painel.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                PainelVetoableChange(evt);
            }
        });

        LabelPrecoVenda.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelPrecoVenda.setText("Preço Unitário:");

        LabelQuantidade.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelQuantidade.setText("Quantidade:");

        TextoFormatadoPrecoUnitario.setEditable(false);
        TextoFormatadoPrecoUnitario.setEnabled(false);
        TextoFormatadoPrecoUnitario.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TextoFormatadoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextoFormatadoQuantidade.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        LabelDesconto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelDesconto.setText("Desconto:");

        TextoFormatadoDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextoFormatadoDesconto.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TextoCodigoProduto.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TextoProduto.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        BotaoBuscarProduto.setBackground(new java.awt.Color(0, 102, 102));
        BotaoBuscarProduto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoBuscarProduto.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoBuscarProduto.setToolTipText("");
        BotaoBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarProdutoActionPerformed(evt);
            }
        });

        LabelCodigoProduto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCodigoProduto.setText("Código:");

        LabelProduto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelProduto.setText("Produto");

        LabelEstoque.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelEstoque.setText("Estoque Atual:");

        TextoFormatadoEstoque.setEditable(false);
        TextoFormatadoEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextoFormatadoEstoque.setEnabled(false);
        TextoFormatadoEstoque.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        BotaoAdicionarProduto.setBackground(new java.awt.Color(0, 102, 102));
        BotaoAdicionarProduto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoAdicionarProduto.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-add-icon_34367.png"))); // NOI18N
        BotaoAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarProdutoActionPerformed(evt);
            }
        });

        BotaoRetirarProduto.setBackground(new java.awt.Color(204, 0, 0));
        BotaoRetirarProduto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoRetirarProduto.setForeground(new java.awt.Color(255, 255, 255));
        BotaoRetirarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-error-icon_34362.png"))); // NOI18N
        BotaoRetirarProduto.setEnabled(false);
        BotaoRetirarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRetirarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInformacoesPessoaisLayout = new javax.swing.GroupLayout(PainelInformacoesPessoais);
        PainelInformacoesPessoais.setLayout(PainelInformacoesPessoaisLayout);
        PainelInformacoesPessoaisLayout.setHorizontalGroup(
            PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoFormatadoPrecoUnitario))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelQuantidade)
                            .addComponent(TextoFormatadoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDesconto)
                            .addComponent(TextoFormatadoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(LabelEstoque)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(TextoFormatadoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoRetirarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCodigoProduto)
                            .addComponent(TextoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(LabelProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(TextoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        PainelInformacoesPessoaisLayout.setVerticalGroup(
            PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodigoProduto)
                    .addComponent(LabelProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPrecoVenda)
                            .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelDesconto)
                                .addComponent(LabelQuantidade)
                                .addComponent(LabelEstoque)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoFormatadoPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFormatadoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFormatadoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFormatadoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BotaoAdicionarProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoRetirarProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61))
        );

        Painel.addTab("Detalhes do Pedido", PainelInformacoesPessoais);

        BotaoGravar.setBackground(new java.awt.Color(0, 102, 102));
        BotaoGravar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoGravar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-check-icon_34365.png"))); // NOI18N
        BotaoGravar.setText("Gravar");
        BotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarActionPerformed(evt);
            }
        });

        BotaoBuscarCliente.setBackground(new java.awt.Color(0, 102, 102));
        BotaoBuscarCliente.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoBuscarCliente.setToolTipText("");
        BotaoBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarClienteActionPerformed(evt);
            }
        });

        BotaoEditar.setBackground(new java.awt.Color(51, 102, 255));
        BotaoEditar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoEditar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/pencil-icon_34383.png"))); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });

        BotaoCancelar.setBackground(new java.awt.Color(204, 0, 0));
        BotaoCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-error-icon_34362.png"))); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        LabelUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelUsuario.setText("Vendedor:");

        TextoCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        TextoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoClienteActionPerformed(evt);
            }
        });

        LabelOrcamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelOrcamento.setText("Orçamento");

        LabelCodigoCliente.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCodigoCliente.setText("Código:");

        TextoCodigoPedido.setEditable(false);
        TextoCodigoPedido.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TabelaProdutosAdicionados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        TabelaProdutosAdicionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade", "Preço Un.", "Desconto", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaProdutosAdicionados);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("TOTAL:");

        TextoFinalTotal.setEditable(false);
        TextoFinalTotal.setForeground(new java.awt.Color(51, 0, 255));
        TextoFinalTotal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("PAGAMENTO:");

        TextoFinalSubtotal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        TextoFinalSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoFinalSubtotalActionPerformed(evt);
            }
        });

        BotaoBuscarOrcamento.setBackground(new java.awt.Color(0, 102, 102));
        BotaoBuscarOrcamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoBuscarOrcamento.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscarOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoBuscarOrcamento.setToolTipText("");
        BotaoBuscarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarOrcamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("SUBTOTAL:");

        ComboBoxPagamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        ComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "À VISTA", "CARTÃO DÉBITO", "CARTÃO CRÉDITO" }));

        TextoFinalDesconto.setForeground(new java.awt.Color(255, 51, 51));
        TextoFinalDesconto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("DESCONTO:");

        TextoCodigoCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("R$");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 51, 51));
        jLabel6.setText("R$");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel1))
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, 0)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextoFinalDesconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(TextoFinalTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TextoFinalSubtotal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BotaoGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotaoEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotaoCancelar, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TextoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BotaoBuscarOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextoCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelOrcamento)
                                    .addGap(55, 55, 55)
                                    .addComponent(LabelCodigoCliente)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelCliente)
                                .addComponent(TextoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(BotaoBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelUsuario)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelOrcamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoBuscarOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCodigoCliente)
                            .addComponent(LabelCliente)
                            .addComponent(LabelUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextoCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotaoBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoFinalSubtotal)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextoFinalDesconto)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextoFinalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoEditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final int key() {

        try (Connection connection = new ConnectionFactory().getConnection()) {
            PedidoDAO dao = new PedidoDAO(connection);
            return dao.next();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
        return 0;

    }

    public void read() {
        try (Connection connection = new ConnectionFactory().getConnection()) {
            DefaultTableModel ListaProdutos = (DefaultTableModel) TabelaProdutosAdicionados.getModel();
            ListaProdutos.setNumRows(0);

            ClienteDAO dao = new ClienteDAO(connection);

            for (PedidoProduto lista : pp) {
                ListaProdutos.addRow(new Object[]{
                    lista.getId(),
                    lista.getProduto().getId(),
                    lista.getQuantidade(),
                    lista.getProduto().getVenda(),
                    lista.getDesconto(),
                    lista.getSubtotal()
                });
            }

            valores();

        } catch (SQLException ex) {
            Logger.getLogger(ConsultaClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpar() {
        TextoCodigoProduto.setText("");
        TextoProduto.setText("");
        TextoFormatadoPrecoUnitario.setText("");
        TextoFormatadoQuantidade.setText("");
        TextoFormatadoEstoque.setText("");
        TextoFormatadoQuantidade.setText("");
        TextoFormatadoDesconto.setText("");
    }

    private void valores() {
        double subtotal = 0;
        double desconto = 0;
        double total = 0;

        for (PedidoProduto lista : pp) {

            subtotal += lista.getSubtotal();
            desconto += lista.getDesconto();
            total += lista.getTotal();

        }

        TextoFinalSubtotal.setText(String.valueOf(subtotal));
        TextoFinalDesconto.setText(String.valueOf(desconto));
        TextoFinalTotal.setText(String.valueOf(total));
    }


    private void BotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarActionPerformed

        gravarPedido();
        gravarPedidoProduto();

    }//GEN-LAST:event_BotaoGravarActionPerformed

    public void gravarPedido() {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            PedidoDAO dao = new PedidoDAO(connection);
            if (transacao == 0) {

                Pedido p;

                p = new Pedido(key(),
                        new Cliente(Integer.valueOf(TextoCodigoCliente.getText())),
                        Double.valueOf(TextoFinalSubtotal.getText()),
                        Double.valueOf(TextoFinalDesconto.getText()),
                        Double.valueOf(TextoFinalTotal.getText()),
                        String.valueOf(ComboBoxPagamento.getSelectedItem())
                );

                dao.create(p);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
    }

    public void gravarPedidoProduto() {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            PedidoProdutoDAO dao = new PedidoProdutoDAO(connection);

            if (transacao == 0) {

                for (PedidoProduto lista : pp) {

                    PedidoProduto p = new PedidoProduto(0,
                            new Pedido(lista.getPedido().getId()),
                            new Produto(lista.getProduto().getId()),
                            lista.getQuantidade(),
                            lista.getSubtotal(),
                            lista.getDesconto(),
                            lista.getTotal());

                    dao.create(p);

                }

                JOptionPane.showMessageDialog(null, "Gravado no banco de dados!");
                //TextoCodigo.setText("");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
    }

    private void BotaoBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarClienteActionPerformed
        if (TextoCodigoCliente.getText().isEmpty()) {
            buscarCliente(0);
        } else {
            buscarCliente(Integer.valueOf(TextoCodigoCliente.getText()));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBuscarClienteActionPerformed

    public void buscarCliente(Integer busca) {

        try (Connection connection = new ConnectionFactory().getConnection()) {

            if (busca != 0) {

                ClienteDAO dao = new ClienteDAO(connection);

                List<Cliente> c = dao.read(busca);
                TextoCodigoCliente.setText(String.valueOf(c.get(0).getId()));
                TextoCliente.setText(c.get(0).getPessoa().getNome());

            } else {
                ConsultaClienteView cliente = new ConsultaClienteView();
                PrincipalView.DesktopPanePrincipal.add(cliente);
                cliente.setVisible(true);
                PrincipalView.DesktopPanePrincipal.setComponentZOrder(cliente, 0);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não conseguimos recuperar essa informação");
        }
    }

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    List<PedidoProduto> pp = new ArrayList<>();

    public void adicionar() {
        Double subtotal = Integer.valueOf(TextoFormatadoQuantidade.getText()) * Double.valueOf(TextoFormatadoPrecoUnitario.getText());
        Double total = subtotal - Double.valueOf(TextoFormatadoDesconto.getText());

        pp.add(new PedidoProduto(0,
                new Pedido(key()),
                produto,
                Integer.valueOf(TextoFormatadoQuantidade.getText()),
                subtotal,
                Double.valueOf(TextoFormatadoDesconto.getText()),
                total
        ));
    }

    private void BotaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarProdutoActionPerformed
        // TODO add your handling code here:

        adicionar();
        limpar();
        read();

    }//GEN-LAST:event_BotaoAdicionarProdutoActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        transacao = 1;

        //TextoCodigo.setEditable(false);
        BotaoEditar.setEnabled(false);
        BotaoAdicionarProduto.setEnabled(false);
        BotaoGravar.setEnabled(true);
        BotaoCancelar.setEnabled(true);
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:

        //TextoCodigo.setEditable(true);
        BotaoAdicionarProduto.setEnabled(true);
        BotaoEditar.setEnabled(false);
        BotaoCancelar.setEnabled(false);
        BotaoGravar.setEnabled(false);
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void PainelVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_PainelVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_PainelVetoableChange

    private void BotaoBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarProdutoActionPerformed
        // TODO add your handling code here:
        if (TextoCodigoProduto.getText().isEmpty()) {
            buscarProduto(0);
        } else {
            buscarProduto(Integer.valueOf(TextoCodigoProduto.getText()));
        }
    }//GEN-LAST:event_BotaoBuscarProdutoActionPerformed

    Produto produto = null;

    public void buscarProduto(Integer busca) {

        try (Connection connection = new ConnectionFactory().getConnection()) {

            if (busca != 0) {

                ProdutoDAO dao = new ProdutoDAO(connection);

                List<Produto> p = dao.read(busca);

                produto = p.get(0);

                TextoCodigoProduto.setText(String.valueOf(p.get(0).getId()));
                TextoProduto.setText(p.get(0).getDescricao());
                TextoFormatadoPrecoUnitario.setText(String.valueOf(p.get(0).getVenda()));
                TextoFormatadoEstoque.setText(String.valueOf(p.get(0).getEstoque()));

            } else {
                ConsultaProdutoView consultaProd = new ConsultaProdutoView();
                PrincipalView.DesktopPanePrincipal.add(consultaProd);
                consultaProd.setVisible(true);
                PrincipalView.DesktopPanePrincipal.setComponentZOrder(consultaProd, 0);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não conseguimos recuperar essa informação");
        }
    }

    private void BotaoBuscarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarOrcamentoActionPerformed
        // TODO add your handling code here:

        if (TextoCodigoPedido.getText().isEmpty()) {
            buscarOrcamento(0);
        } else {
            buscarOrcamento(12);
            //buscarOrcamento(Integer.valueOf(TextoCodigoProduto.getText()));
        }
    }//GEN-LAST:event_BotaoBuscarOrcamentoActionPerformed

    private void buscarOrcamento(Integer busca) {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            if (busca != 0) {

                PedidoDAO dao = new PedidoDAO(connection);

                List<Pedido> p = dao.read(Integer.valueOf(TextoCodigoPedido.getText()));

                TextoCodigoPedido.setText(String.valueOf(p.get(0).getId()));
                TextoCliente.setText(String.valueOf(p.get(0).getCliente().getPessoa().getNome()));
                ComboBoxPagamento.setSelectedItem(p.get(0).getPagamento());
                TextoFinalSubtotal.setText(String.valueOf(p.get(0).getSubtotal()));
                TextoFinalDesconto.setText(String.valueOf(p.get(0).getDesconto()));
                TextoFinalTotal.setText(String.valueOf(p.get(0).getTotal()));
            } else {
                ConsultaVendaView venda = new ConsultaVendaView();
                PrincipalView.DesktopPanePrincipal.add(venda);
                venda.setVisible(true);
                PrincipalView.DesktopPanePrincipal.setComponentZOrder(venda, 0);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não conseguimos recuperar essa informação");
        }
    }

    private void BotaoRetirarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRetirarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRetirarProdutoActionPerformed

    private void TextoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoClienteActionPerformed

    private void TextoFinalSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoFinalSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoFinalSubtotalActionPerformed

    public void capturarOrcamento(Pedido pedido) {

        TextoCodigoPedido.setText(String.valueOf(pedido.getId()));
        TextoCodigoCliente.requestFocus();
        buscarOrcamento(pedido.getId());
    }

    public void capturarCliente(Cliente cliente) {

        TextoCodigoCliente.setText(String.valueOf(cliente.getId()));
        TextoCodigoCliente.requestFocus();
        buscarCliente(cliente.getId());
    }

    public void capturarProduto(Produto produto) {

        TextoCodigoProduto.setText(String.valueOf(produto.getId()));
        TextoCodigoProduto.requestFocus();
        buscarProduto(produto.getId());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicionarProduto;
    private javax.swing.JButton BotaoBuscarCliente;
    private javax.swing.JButton BotaoBuscarOrcamento;
    private javax.swing.JButton BotaoBuscarProduto;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoRetirarProduto;
    private javax.swing.JComboBox<String> ComboBoxPagamento;
    private javax.swing.JDialog DialogCliente;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelCodigoCliente;
    private javax.swing.JLabel LabelCodigoProduto;
    private javax.swing.JLabel LabelDesconto;
    private javax.swing.JLabel LabelEstoque;
    private javax.swing.JLabel LabelOrcamento;
    private javax.swing.JLabel LabelPrecoVenda;
    private javax.swing.JLabel LabelProduto;
    private javax.swing.JLabel LabelQuantidade;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTabbedPane Painel;
    private javax.swing.JPanel PainelInformacoesPessoais;
    private javax.swing.JTable TabelaProdutosAdicionados;
    private javax.swing.JTextField TextoCliente;
    public static javax.swing.JTextField TextoCodigoCliente;
    public static javax.swing.JTextField TextoCodigoPedido;
    public static javax.swing.JTextField TextoCodigoProduto;
    private javax.swing.JFormattedTextField TextoFinalDesconto;
    private javax.swing.JFormattedTextField TextoFinalSubtotal;
    private javax.swing.JFormattedTextField TextoFinalTotal;
    private javax.swing.JFormattedTextField TextoFormatadoDesconto;
    private javax.swing.JFormattedTextField TextoFormatadoEstoque;
    private javax.swing.JFormattedTextField TextoFormatadoPrecoUnitario;
    private javax.swing.JFormattedTextField TextoFormatadoQuantidade;
    private javax.swing.JTextField TextoProduto;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
