package br.com.uemg.autopecas.view;

import br.com.uemg.autopecas.DAO.CategoriaDAO;
import br.com.uemg.autopecas.DAO.FornecedorDAO;
import br.com.uemg.autopecas.DAO.ProdutoDAO;
import br.com.uemg.autopecas.controller.ConnectionFactory;
import br.com.uemg.autopecas.model.Categoria;
import br.com.uemg.autopecas.model.Fornecedor;
import br.com.uemg.autopecas.model.Produto;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class VendaView extends javax.swing.JInternalFrame {

    public int transacao;

    /**
     * Creates new form Cliente
     */
    public VendaView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDescricao = new javax.swing.JLabel();
        TextoDescricao = new javax.swing.JTextField();
        Painel = new javax.swing.JTabbedPane();
        PainelInformacoesPessoais = new javax.swing.JPanel();
        LabelPrecoVenda = new javax.swing.JLabel();
        LabelEstoque = new javax.swing.JLabel();
        TextoFormatadoPrecoVenda = new javax.swing.JFormattedTextField();
        TextoFormatadoEstoque = new javax.swing.JFormattedTextField();
        LabelQuantidade = new javax.swing.JLabel();
        TextoFormatadoQuantidade = new javax.swing.JFormattedTextField();
        TextoCodigo3 = new javax.swing.JTextField();
        TextoDescricao2 = new javax.swing.JTextField();
        BotaoBuscar1 = new javax.swing.JButton();
        LabelCodigo3 = new javax.swing.JLabel();
        LabelDescricao2 = new javax.swing.JLabel();
        LabelQuantidade1 = new javax.swing.JLabel();
        TextoFormatadoQuantidade1 = new javax.swing.JFormattedTextField();
        BotaoNovo = new javax.swing.JButton();
        BotaoCancelar1 = new javax.swing.JButton();
        BotaoGravar = new javax.swing.JButton();
        BotaoBuscar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        LabelDescricao1 = new javax.swing.JLabel();
        TextoDescricao1 = new javax.swing.JTextField();
        LabelCodigo1 = new javax.swing.JLabel();
        LabelCodigo2 = new javax.swing.JLabel();
        TextoCodigo2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        BotaoBuscar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoCodigo4 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Ordem de Vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N
        setClosable(true);
        setForeground(java.awt.Color.white);
        setMaximizable(true);
        setResizable(true);
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInputVerifier(getInputVerifier());
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        LabelDescricao.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelDescricao.setText("Cliente");

        TextoDescricao.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        Painel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Painel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        Painel.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                PainelVetoableChange(evt);
            }
        });

        LabelPrecoVenda.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelPrecoVenda.setText("Preço Venda:");

        LabelEstoque.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelEstoque.setText("Quantidade:");

        TextoFormatadoPrecoVenda.setEditable(false);
        TextoFormatadoPrecoVenda.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TextoFormatadoEstoque.setEditable(false);
        TextoFormatadoEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextoFormatadoEstoque.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        LabelQuantidade.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelQuantidade.setText("Desconto:");

        TextoFormatadoQuantidade.setEditable(false);
        TextoFormatadoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextoFormatadoQuantidade.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TextoCodigo3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        TextoDescricao2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        BotaoBuscar1.setBackground(new java.awt.Color(0, 102, 102));
        BotaoBuscar1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoBuscar1.setToolTipText("");
        BotaoBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscar1ActionPerformed(evt);
            }
        });

        LabelCodigo3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCodigo3.setText("Código:");

        LabelDescricao2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelDescricao2.setText("Produto");

        LabelQuantidade1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelQuantidade1.setText("Estoque Atual:");

        TextoFormatadoQuantidade1.setEditable(false);
        TextoFormatadoQuantidade1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextoFormatadoQuantidade1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        BotaoNovo.setBackground(new java.awt.Color(0, 102, 102));
        BotaoNovo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoNovo.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-add-icon_34367.png"))); // NOI18N
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });

        BotaoCancelar1.setBackground(new java.awt.Color(204, 0, 0));
        BotaoCancelar1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-error-icon_34362.png"))); // NOI18N
        BotaoCancelar1.setEnabled(false);
        BotaoCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInformacoesPessoaisLayout = new javax.swing.GroupLayout(PainelInformacoesPessoais);
        PainelInformacoesPessoais.setLayout(PainelInformacoesPessoaisLayout);
        PainelInformacoesPessoaisLayout.setHorizontalGroup(
            PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoFormatadoPrecoVenda))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEstoque)
                            .addComponent(TextoFormatadoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelQuantidade)
                            .addComponent(TextoFormatadoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(LabelQuantidade1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(TextoFormatadoQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCodigo3)
                            .addComponent(TextoCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(LabelDescricao2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                                .addComponent(TextoDescricao2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        PainelInformacoesPessoaisLayout.setVerticalGroup(
            PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesPessoaisLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodigo3)
                    .addComponent(LabelDescricao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextoCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInformacoesPessoaisLayout.createSequentialGroup()
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPrecoVenda)
                            .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelQuantidade)
                                .addComponent(LabelEstoque)
                                .addComponent(LabelQuantidade1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoFormatadoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFormatadoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFormatadoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInformacoesPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoFormatadoQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotaoNovo))
                    .addComponent(BotaoCancelar1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61))
        );

        Painel.addTab("Detalhes do Pedido", PainelInformacoesPessoais);

        BotaoGravar.setBackground(new java.awt.Color(0, 102, 102));
        BotaoGravar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoGravar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-check-icon_34365.png"))); // NOI18N
        BotaoGravar.setText("Gravar");
        BotaoGravar.setEnabled(false);
        BotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarActionPerformed(evt);
            }
        });

        BotaoBuscar.setBackground(new java.awt.Color(0, 102, 102));
        BotaoBuscar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoBuscar.setToolTipText("");
        BotaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarActionPerformed(evt);
            }
        });

        BotaoEditar.setBackground(new java.awt.Color(51, 102, 255));
        BotaoEditar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoEditar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/pencil-icon_34383.png"))); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.setEnabled(false);
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });

        BotaoCancelar.setBackground(new java.awt.Color(204, 0, 0));
        BotaoCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/sign-error-icon_34362.png"))); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.setEnabled(false);
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        BotaoExcluir.setBackground(new java.awt.Color(204, 0, 0));
        BotaoExcluir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        BotaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/trashcan-full-icon_34338.png"))); // NOI18N
        BotaoExcluir.setText("Excluir");
        BotaoExcluir.setEnabled(false);
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        LabelDescricao1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelDescricao1.setText("Vendedor:");

        TextoDescricao1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        TextoDescricao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDescricao1ActionPerformed(evt);
            }
        });

        LabelCodigo1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCodigo1.setText("Orçamento");

        LabelCodigo2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelCodigo2.setText("Código:");

        TextoCodigo2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jTable1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Quantidade", "Valor Un.", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("TOTAL:");

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setForeground(new java.awt.Color(51, 0, 255));
        jFormattedTextField1.setText("R$ 245,56");
        jFormattedTextField1.setFont(new java.awt.Font("Liberation Sans", 1, 26)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("PAGAMENTO:");

        jFormattedTextField2.setText("R$ 245,56");
        jFormattedTextField2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N

        BotaoBuscar2.setBackground(new java.awt.Color(0, 102, 102));
        BotaoBuscar2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/uemg/autopecas/assets/search-icon_34373.png"))); // NOI18N
        BotaoBuscar2.setToolTipText("");
        BotaoBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscar2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("SUBTOTAL:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFormattedTextField3.setText("R$ 245,56");
        jFormattedTextField3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("DESCONTO:");

        TextoCodigo4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextField1)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotaoGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoCancelar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotaoBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextoCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelCodigo1)
                                        .addGap(55, 55, 55)
                                        .addComponent(LabelCodigo2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDescricao)
                                    .addComponent(TextoDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BotaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelDescricao1))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCodigo2)
                            .addComponent(LabelDescricao)
                            .addComponent(LabelDescricao1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextoCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void populaComboBoxCategorias() {

        try (Connection connection = new ConnectionFactory().getConnection()) {
            CategoriaDAO dao = new CategoriaDAO(connection);
            List<Categoria> categoria = new ArrayList<>();
            categoria = dao.read();

            for (Categoria c : categoria) {
                //ComboBoxCategoria.addItem(c);

            }
        } catch (SQLException ex) {
        }
    }

    private void BotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarActionPerformed

        gravar();
        //TextoCodigo.setEnabled(false);
        BotaoNovo.setEnabled(true);
        BotaoEditar.setEnabled(true);
    }//GEN-LAST:event_BotaoGravarActionPerformed

    public void gravar() {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            ProdutoDAO dao = new ProdutoDAO(connection);
            if (transacao == 0) {

                Produto p = new Produto( // 0,
                        // (Categoria) ComboBoxCategoria.getSelectedItem(),
                        // (Fornecedor) ComboBoxFornecedor.getSelectedItem(),
                        // TextoDescricao.getText(),
                        // Double.valueOf(TextoFormatadoPrecoCusto.getText()),
                        // Double.valueOf(TextoFormatadoPrecoVenda.getText()),
                        // Integer.valueOf(TextoFormatadoEstoque.getText()),
                        // Integer.valueOf(TextoFormatadoEstoque.getText()),
                        // String.valueOf(ComboBoxTipoUnidade.getSelectedIndex())
                        );
                dao.create(p);

                JOptionPane.showMessageDialog(null, "Gravado no banco de dados!");
                //TextoCodigo.setText("");
                campos(false);
            }
            if (transacao == 1) {

                Produto p = new Produto( //0,
                        // (Categoria) ComboBoxCategoria.getSelectedItem(),
                        // (Fornecedor) ComboBoxFornecedor.getSelectedItem(),
                        // TextoDescricao.getText(),
                        // Double.valueOf(TextoFormatadoPrecoCusto.getText()),
                        // Double.valueOf(TextoFormatadoPrecoVenda.getText()),
                        // Integer.valueOf(TextoFormatadoEstoque.getText()),
                        // Integer.valueOf(TextoFormatadoEstoque.getText()),
                        // String.valueOf(ComboBoxTipoUnidade.getSelectedIndex())
                        );
                System.out.println(p);
                dao.update(p);

                JOptionPane.showMessageDialog(null, "Gravado no banco de dados!");
                campos(false);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
    }

    private void BotaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarActionPerformed
        /*if (TextoCodigo.getText().isEmpty()) {
            buscar(0);
            BotaoNovo.setEnabled(true);
        } else {
            buscar(Integer.valueOf(TextoCodigo.getText()));
            BotaoEditar.setEnabled(true);

        }*/

        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBuscarActionPerformed

    public void buscar(Integer busca) {

        try (Connection connection = new ConnectionFactory().getConnection()) {

            if (busca != 0) {

                ProdutoDAO dao = new ProdutoDAO(connection);

                List<Produto> p = dao.read(busca);

                //TextoCodigo.setEditable(false);
                BotaoEditar.setEnabled(true);
                preencher(p);
                campos(false);
            } else {
                //TextoCodigo.setEnabled(false);
                ConsultaProdutoView produto = new ConsultaProdutoView();
                PrincipalView.DesktopPanePrincipal.add(produto);
                produto.setVisible(true);
                PrincipalView.DesktopPanePrincipal.setComponentZOrder(produto, 0);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não conseguimos recuperar essa informação");
        }
    }

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        // TODO add your handling code here:
        transacao = 0;
        limpar();
        campos(true);

        //TextoCodigo.setEditable(false);
        BotaoNovo.setEnabled(false);
        BotaoExcluir.setEnabled(false);
        BotaoEditar.setEnabled(false);
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        transacao = 1;
        campos(true);

        //TextoCodigo.setEditable(false);
        BotaoEditar.setEnabled(false);
        BotaoNovo.setEnabled(false);
        BotaoGravar.setEnabled(true);
        BotaoCancelar.setEnabled(true);
        BotaoExcluir.setEnabled(true);
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:
        campos(false);

        //TextoCodigo.setEditable(true);
        BotaoNovo.setEnabled(true);
        BotaoEditar.setEnabled(false);
        BotaoCancelar.setEnabled(false);
        BotaoGravar.setEnabled(false);
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void PainelVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_PainelVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_PainelVetoableChange

    private void BotaoBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBuscar1ActionPerformed

    private void TextoDescricao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDescricao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDescricao1ActionPerformed

    private void BotaoBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBuscar2ActionPerformed

    private void BotaoCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCancelar1ActionPerformed

    public void excluir() {
        try (Connection connection = new ConnectionFactory().getConnection()) {

            if (JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?", "Confirmação de exclusão!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                ProdutoDAO dao = new ProdutoDAO(connection);
                Produto p = new Produto();

                //Integer id = Integer.valueOf(
                //TextoCodigo.getText());
                //p.setId(id);
                dao.delete(p);
                limpar();
            }

            JOptionPane.showMessageDialog(null, "Excluído no Banco de Dados");
            campos(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível concluir a solicitação");
        }
    }

    public void capturar(Produto produto) {

        //TextoCodigo.setText(String.valueOf(produto.getId()));
        //TextoCodigo.requestFocus();
    }

    public void preencher(List<Produto> produto) {

        //TextoCodigo.setText(String.valueOf(produto.get(0).getId()));
        //TextoDescricao.setText(produto.get(0).getDescricao());
        //ComboBoxCategoria.setSelectedItem(produto.get(0).getCategoria());
        //ComboBoxFornecedor.setSelectedItem(produto.get(0).getFornecedor());
        // TextoFormatadoPrecoCusto.setText(String.valueOf(produto.get(0).getCusto()));
        // TextoFormatadoPrecoVenda.setText(String.valueOf(produto.get(0).getVenda()));
        // TextoFormatadoEstoque.setText(String.valueOf(produto.get(0).getEstoque()));
        // TextoFormatadoQuantidade.setText(String.valueOf(produto.get(0).getQuantidade()));
        //ComboBoxTipoUnidade.setSelectedIndex(Integer.parseInt(produto.get(0).getUnidade()));
    }

    public void limpar() {

        // TextoCodigo.setText("");
        TextoDescricao.setText("");
        // ComboBoxCategoria.setSelectedItem("");
        
        //  TextoFormatadoPrecoCusto.setText("");
        TextoFormatadoPrecoVenda.setText("");
        TextoFormatadoEstoque.setText("");
        TextoFormatadoQuantidade.setText("");
        // ComboBoxTipoUnidade.setSelectedIndex(0);
    }

    public void campos(boolean status) {

        TextoDescricao.setEditable(status);
        // ComboBoxCategoria.setEnabled(status);
        
        // TextoFormatadoPrecoCusto.setEditable(status);
        TextoFormatadoPrecoVenda.setEditable(status);
        TextoFormatadoEstoque.setEditable(status);
        TextoFormatadoQuantidade.setEditable(status);
        // ComboBoxTipoUnidade.setEnabled(status);
        BotaoCancelar.setEnabled(status);
        BotaoEditar.setEnabled(status);
        BotaoGravar.setEnabled(status);
        BotaoExcluir.setEnabled(status);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscar;
    private javax.swing.JButton BotaoBuscar1;
    private javax.swing.JButton BotaoBuscar2;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoCancelar1;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JLabel LabelCodigo1;
    private javax.swing.JLabel LabelCodigo2;
    private javax.swing.JLabel LabelCodigo3;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JLabel LabelDescricao1;
    private javax.swing.JLabel LabelDescricao2;
    private javax.swing.JLabel LabelEstoque;
    private javax.swing.JLabel LabelPrecoVenda;
    private javax.swing.JLabel LabelQuantidade;
    private javax.swing.JLabel LabelQuantidade1;
    private javax.swing.JTabbedPane Painel;
    private javax.swing.JPanel PainelInformacoesPessoais;
    public static javax.swing.JTextField TextoCodigo2;
    public static javax.swing.JTextField TextoCodigo3;
    public static javax.swing.JTextField TextoCodigo4;
    private javax.swing.JTextField TextoDescricao;
    private javax.swing.JTextField TextoDescricao1;
    private javax.swing.JTextField TextoDescricao2;
    private javax.swing.JFormattedTextField TextoFormatadoEstoque;
    private javax.swing.JFormattedTextField TextoFormatadoPrecoVenda;
    private javax.swing.JFormattedTextField TextoFormatadoQuantidade;
    private javax.swing.JFormattedTextField TextoFormatadoQuantidade1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
